name: gwacheonhs_app
description: An application for Gwacheon High School

publish_to: "none"

version: 1.1.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.9
  dio: ^3.0.9
  rxdart: ^0.23.1
  intl: ^0.16.1
  table_calendar: ^2.2.2
  flutter_html: ^1.0.0-pre.1
  url_launcher: ^5.4.2
  path_provider: ^1.6.1
  eva_icons_flutter: ^2.0.1
  package_info: ^0.4.0+14
  device_info: ^0.4.2+1
  firebase_core: "^0.5.0+1"
  firebase_crashlytics: "^0.2.1+1"
  firebase_analytics: "^6.0.2"
  firebase_database: "^4.1.1"
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner: ^1.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/
